services:
  postgres:
    image: postgres:16
    container_name: workshop_postgress
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-workshop_db}
    ports:
      - "5432:5432"
    volumes:
      - ./localdev/data/workshop_pgdata:/var/lib/postgresql/data
